# Generated by Django 4.2.25 on 2025-11-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_material_dimensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('qora', 'Qora'), ('oq', 'Oq'), ('qizil', 'Qizil'), ("ko'k", "Ko'k"), ('yashil', 'Yashil'), ('sariq', 'Sariq'), ('pushti', 'Pushti'), ('jigarrang', 'Jigarrang'), ('kulrang', 'Kulrang'), ("to'q-ko'k", "To'q ko'k"), ('binafsha', 'Binafsha'), ('apelsin', 'Apelsin')], max_length=50, null=True, verbose_name='Rang'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=10, null=True, verbose_name="O'lcham"),
        ),
    ]
