# Generated by Django 4.2.25 on 2025-11-16 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0006_cart_order_remove_product_color_remove_product_size_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="uzum_link",
        ),
        migrations.RemoveField(
            model_name="product",
            name="yandex_market_link",
        ),
    ]
