# Generated by Django 4.2.25 on 2025-11-16 14:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0007_remove_product_uzum_link_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Yaratildi"),
                            ("update", "Yangilandi"),
                            ("delete", "O'chirildi"),
                            ("activate", "Faollashtirildi"),
                            ("deactivate", "Nofaol qilindi"),
                        ],
                        max_length=20,
                        verbose_name="Harakat",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        choices=[
                            ("product", "Mahsulot"),
                            ("category", "Kategoriya"),
                            ("tag", "Tag"),
                            ("order", "Buyurtma"),
                        ],
                        max_length=50,
                        verbose_name="Model",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(verbose_name="Ob'ekt ID")),
                (
                    "object_repr",
                    models.CharField(max_length=200, verbose_name="Ob'ekt nomi"),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        help_text="O'zgargan maydonlar va qiymatlari",
                        null=True,
                        verbose_name="O'zgarishlar",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Vaqt"
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin harakat logi",
                "verbose_name_plural": "Admin harakat loglari",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="products/gallery/", verbose_name="Rasm"
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Alt Text (SEO)"
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="Tartib raqami"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Mahsulot rasmi",
                "verbose_name_plural": "Mahsulot rasmlari",
                "ordering": ["display_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Tag nomi"
                    ),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "color",
                    models.CharField(
                        default="#000000",
                        help_text="Masalan: #FF0000",
                        max_length=7,
                        verbose_name="Rang (hex)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Taglar",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["display_order", "name"],
                "verbose_name": "Kategoriya",
                "verbose_name_plural": "Kategoriyalar",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="display_order",
            field=models.IntegerField(default=0, verbose_name="Tartib raqami"),
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="categories/",
                verbose_name="Kategoriya rasmi",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Faol"),
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="products.category",
                verbose_name="Asosiy kategoriya",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="product",
            name="meta_description",
            field=models.TextField(blank=True, verbose_name="SEO Description"),
        ),
        migrations.AddField(
            model_name="product",
            name="meta_title",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="SEO Title"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sku",
            field=models.CharField(
                blank=True,
                help_text="Mahsulot artikuli - avtomatik yaratiladi",
                max_length=100,
                unique=True,
                verbose_name="SKU (Stock Keeping Unit)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="products.category",
                verbose_name="Kategoriya",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="discount_percentage",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Chegirma foizi (0-100)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True, verbose_name="Faol"),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_featured",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Mashhur"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Narx (so'm)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("new", "Yangi"),
                    ("discount", "Chegirmadagi"),
                    ("regular", "Oddiy"),
                ],
                db_index=True,
                default="regular",
                max_length=20,
                verbose_name="Mahsulot turi",
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["slug"], name="products_ca_slug_da4386_idx"),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["parent"], name="products_ca_parent__f3c24e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["is_active"], name="products_ca_is_acti_a2d000_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["sku"], name="products_pr_sku_ca0cdc_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "is_active"], name="products_pr_categor_50f5f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["price"], name="products_pr_price_9b1a5f_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["created_at"], name="products_pr_created_52f0d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_featured", "is_active"],
                name="products_pr_is_feat_a1ecf6_idx",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="additional_images",
                to="products.product",
                verbose_name="Mahsulot",
            ),
        ),
        migrations.AddField(
            model_name="adminactionlog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admin_actions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Administrator",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="products.tag",
                verbose_name="Taglar",
            ),
        ),
        migrations.AddIndex(
            model_name="productimage",
            index=models.Index(
                fields=["product", "display_order"],
                name="products_pr_product_48d699_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="adminactionlog",
            index=models.Index(
                fields=["user", "timestamp"], name="products_ad_user_id_fc8cd0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adminactionlog",
            index=models.Index(
                fields=["model_name", "object_id"],
                name="products_ad_model_n_19f387_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="adminactionlog",
            index=models.Index(fields=["action"], name="products_ad_action_e1146a_idx"),
        ),
    ]
